### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by denizzzka** [StrumentiResistenti/Tagsistant#11]
Core dumped after I am trying to enter to the directory by Dolphin GUI

```
$ gdb /usr/local/bin/tagsistant /tmp/core.tagsis*
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/tagsistant...done.
[New LWP 4265]
[New LWP 4777]
[New LWP 4263]
[New LWP 4266]
[New LWP 4261]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `tagsistant /home/denizzz/Tagged/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  tagsistant_query_add_and_set (statement=0x7f454400ea60, and_set=0x0) at rds.c:91
91		if (and_set->value && strlen(and_set->value)) {
(gdb) bt
#0  tagsistant_query_add_and_set (statement=0x7f454400ea60, and_set=0x0) at rds.c:91
#1  0x000000000040f859 in tagsistant_materialize_rds (qtree=qtree@entry=0x7f454c05f410) at rds.c:286
#2  0x00000000004088f8 in tagsistant_querytree_check_tagging_consistency (qtree=qtree@entry=0x7f454c05f410) at path_resolution.c:384
#3  0x0000000000410448 in tagsistant_getattr (path=0x7f454c05f5c0 "/store/@/.directory", stbuf=0x7f4559ac4b90) at fuse_operations/getattr.c:113
#4  0x00007f455d8d09c8 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#5  0x00007f455d8d0bb8 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#6  0x00007f455d8db895 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#7  0x00007f455d8d8394 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#8  0x00007f455ce1e0a4 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#9  0x00007f455cb5304d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

```
  Tagsistant (tagfs) v.0.8.2 (codename: Athens) 
  Build: 576.20150726.000003 FUSE_USE_VERSION: 26
  Semantic File System for Linux kernels
  (c) 2006-2015 Tx0 <tx0@strumentiresistenti.org>
```

**Comment by denizzzka** [comment]
Try:

```
$ tagsistant -s -f --debug=F ~/Tagged
```
core dumps after enetring into ./store by Dolphin

```
$ gdb /usr/local/bin/tagsistant /tmp/core.tagsistant.1444006042.1000.1000.11891
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/tagsistant...done.
[New LWP 11891]
[New LWP 11893]
[New LWP 11892]
[New LWP 11894]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `tagsistant -s -f --debug=F /home/denizzz/Tagged'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  tagsistant_query_add_and_set (statement=0x9284a0, and_set=0x0) at rds.c:91
91		if (and_set->value && strlen(and_set->value)) {
(gdb) bt
#0  tagsistant_query_add_and_set (statement=0x9284a0, and_set=0x0) at rds.c:91
#1  0x000000000040f859 in tagsistant_materialize_rds (qtree=qtree@entry=0x99f4d0) at rds.c:286
#2  0x00000000004088f8 in tagsistant_querytree_check_tagging_consistency (qtree=qtree@entry=0x99f4d0) at path_resolution.c:384
#3  0x0000000000410448 in tagsistant_getattr (path=0x99a120 "/store/@/.directory", stbuf=0x7ffc5ac02370) at fuse_operations/getattr.c:113
#4  0x00007f7f7168a9c8 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#5  0x00007f7f7168abb8 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#6  0x00007f7f71695895 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#7  0x00007f7f71691f9c in fuse_session_loop () from /lib/x86_64-linux-gnu/libfuse.so.2
#8  0x00007f7f7168a4e8 in fuse_loop () from /lib/x86_64-linux-gnu/libfuse.so.2
#9  0x00007f7f7169a8e7 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#10 0x0000000000407264 in main (argc=1, argv=0x7ffc5ac02a48) at tagsistant.c:702
(gdb) 
= 
```

**Comment by StrumentiResistenti** [comment]
I've made a patch, could you please pull it and check it?

**Comment by denizzzka** [comment]
core dumps in the another place:

```
$ gdb /usr/local/bin/tagsistant /tmp/core.tagsistant.1444088728.1000.1000.30995
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/tagsistant...done.
[New LWP 30995]
[New LWP 30997]
[New LWP 30996]
[New LWP 30998]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/tagsistant -s -f --debug=F /home/denizzz/Tagged'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000040f8cd in tagsistant_materialize_rds (qtree=qtree@entry=0x1626440) at rds.c:298
298			qtree_and_node *related = query->and_set->related;
(gdb) bt
#0  0x000000000040f8cd in tagsistant_materialize_rds (qtree=qtree@entry=0x1626440) at rds.c:298
#1  0x00000000004088f8 in tagsistant_querytree_check_tagging_consistency (qtree=qtree@entry=0x1626440) at path_resolution.c:384
#2  0x00000000004104b8 in tagsistant_getattr (path=0x161f6f0 "/store/@/.directory", stbuf=0x7ffe8901b7b0) at fuse_operations/getattr.c:113
#3  0x00007fb8452989c8 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#4  0x00007fb845298bb8 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#5  0x00007fb8452a3895 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#6  0x00007fb84529ff9c in fuse_session_loop () from /lib/x86_64-linux-gnu/libfuse.so.2
#7  0x00007fb8452984e8 in fuse_loop () from /lib/x86_64-linux-gnu/libfuse.so.2
#8  0x00007fb8452a88e7 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#9  0x0000000000407264 in main (argc=1, argv=0x7ffe8901be88) at tagsistant.c:702
```

**Comment by denizzzka** [comment]
also, tried:
```
$ /usr/local/bin/tagsistant -s -f --debug=f ~/Tagged
```
it isn't shows any debugging messages.

```
$ gdb /usr/local/bin/tagsistant /tmp/core.tagsistant.1444089736.1000.1000.2036
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/tagsistant...done.
[New LWP 2036]
[New LWP 2037]
[New LWP 2038]
[New LWP 2039]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/local/bin/tagsistant -s -f --debug=f /home/denizzz/Tagged'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000040f8cd in tagsistant_materialize_rds (qtree=qtree@entry=0xf8ab70) at rds.c:298
298			qtree_and_node *related = query->and_set->related;
(gdb) bt
#0  0x000000000040f8cd in tagsistant_materialize_rds (qtree=qtree@entry=0xf8ab70) at rds.c:298
#1  0x00000000004088f8 in tagsistant_querytree_check_tagging_consistency (qtree=qtree@entry=0xf8ab70) at path_resolution.c:384
#2  0x00000000004104b8 in tagsistant_getattr (path=0xf86300 "/store/@/.directory", stbuf=0x7fff2efb6390) at fuse_operations/getattr.c:113
#3  0x00007f8f638779c8 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#4  0x00007f8f63877bb8 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#5  0x00007f8f63882895 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#6  0x00007f8f6387ef9c in fuse_session_loop () from /lib/x86_64-linux-gnu/libfuse.so.2
#7  0x00007f8f638774e8 in fuse_loop () from /lib/x86_64-linux-gnu/libfuse.so.2
#8  0x00007f8f638878e7 in ?? () from /lib/x86_64-linux-gnu/libfuse.so.2
#9  0x0000000000407264 in main (argc=1, argv=0x7fff2efb6a68) at tagsistant.c:702
(gdb) 
```

**Comment by StrumentiResistenti** [comment]
I've pushed another patch, please pull it and test it.

**Comment by denizzzka** [comment]
It works, thanks!
